networks:
  counter-net:

volumes:
  counter-vol:
  
services:
  my_app:
    build: .
    command: node index.js
    ports:
      - target: 3000
        published: 3000
    networks:
      - counter-net
    volumes:
      - type: volume
        source: counter-vol
        target: /app
  redis:
    image: "redis:alpine"
    networks:
      counter-net:
  nginx:
    image: nginx
    container_name: nginx_container
    ports:
        - target: 80
          published: 3001
    networks: 
        - counter-net
    depends_on:
        - my_app
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - counter-vol:/var/lib/postgresql/data
