apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-spring
  namespace: prova-devops
spec:
  selector:
    matchLabels:
      app: app-spring
  template:
    metadata:
      labels:
        app: app-spring
    spec:
      containers:
      - name: app-spring
        image: daniloufla/app-spring:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
